---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-job-notifier
rules:
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/logs
      - pods/log
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-job-notifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-job-notifier
subjects:
  - kind: ServiceAccount
    name: kube-job-notifier
    namespace: kube-job-notifier