apiVersion: batch/v1
kind: Job
metadata:
  name: failing-test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: failing-container
          image: busybox
          command: ["/bin/sh"]
          args:
            - -c
            - 'echo "It works!" && exit 1'
